# Generated by Django 6.0.2 on 2026-05-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="students",
            options={
                "ordering": ["name"],
                "verbose_name": "Dossier Etudiant",
                "verbose_name_plural": "Dossiers Etudiants",
            },
        ),
    ]
