# Generated by Django 6.0.2 on 2026-05-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="core",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="logo/", verbose_name="Logo de l'école"
            ),
        ),
    ]
