# Generated by Django 6.0.2 on 2026-05-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_core_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="core",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="core",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Date de création"
            ),
        ),
        migrations.AddField(
            model_name="core",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
