# Generated by Django 6.0.2 on 2026-05-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_core_created_at_core_date_created_core_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="core",
            name="date_created",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de création"
            ),
        ),
    ]
