# Generated by Django 6.0.2 on 2026-05-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_core_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="core",
            name="date_created",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de création"
            ),
        ),
    ]
