# Generated by Django 6.0.2 on 2026-05-11 17:31

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'db_table': 'role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('surname', models.CharField(max_length=100, verbose_name='Post Nom')),
                ('firstname', models.CharField(max_length=100, verbose_name='Prenom')),
                ('sexe', models.CharField(choices=[('masculin', 'Masculin'), ('féminin', 'Feminin')], default='masculin', max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CD', unique=True, verbose_name='Contact📞')),
                ('title', models.CharField(blank=True, choices=[('Mr.', 'Monsieur'), ('Mme.', 'Madame'), ('Mlle.', 'Mademoiselle'), ('Me.', 'Maitre'), ('Dr.', 'Docteur'), ('Pr.', 'Professeur')], max_length=60, null=True, verbose_name='Titre')),
                ('degree', models.CharField(blank=True, max_length=100, null=True, verbose_name="Niveau d'etude")),
                ('faculty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Domaine')),
                ('matricule', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('date_birthday', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('admin', models.BooleanField(default=False, null=True, verbose_name='Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ManyToManyField(blank=True, to='staff.role')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fonctionnaire',
                'verbose_name_plural': 'fonctionnaires',
                'db_table': 'staff',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de nommination')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin mandat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ManyToManyField(blank=True, to='education.course')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.options')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.section')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'verbose_name': "Titulaire d'option",
                'verbose_name_plural': "Titulaires d'options",
                'db_table': 'Dean',
            },
        ),
    ]
