# Generated by Django 6.0.2 on 2026-05-11 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.staff'),
        ),
        migrations.AddField(
            model_name='courses',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.options'),
        ),
        migrations.AddField(
            model_name='courses',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.section'),
        ),
        migrations.AddField(
            model_name='tutors',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.classes'),
        ),
        migrations.AddField(
            model_name='tutors',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.options'),
        ),
        migrations.AddField(
            model_name='tutors',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.section'),
        ),
        migrations.AddField(
            model_name='tutors',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
    ]
