# Generated by Django 6.0.2 on 2026-05-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="options",
            name="code",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Code d'option"
            ),
        ),
    ]
