# Generated by Django 6.0.2 on 2026-05-11 17:31

import django.db.models.deletion
import phonenumber_field.modelfields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField(null=True, verbose_name='Description')),
                ('mission', tinymce.models.HTMLField(null=True, verbose_name='Notre mission')),
                ('values', tinymce.models.HTMLField(null=True, verbose_name='Nos valeur')),
                ('vision', tinymce.models.HTMLField(null=True, verbose_name='Notre vision')),
                ('image', models.ImageField(null=True, upload_to='about_images/', verbose_name='photo de batiment')),
                ('image_2', models.ImageField(null=True, upload_to='about_images/', verbose_name="photo d'eleves")),
                ('team', models.ImageField(blank=True, null=True, upload_to='about_images/', verbose_name="photo d'equipe")),
            ],
            options={
                'verbose_name': 'A propo',
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CD', unique=True, verbose_name='Téléphone')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('hours_operation', tinymce.models.HTMLField(blank=True, verbose_name='Heure de travail')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titre')),
                ('message', models.TextField(max_length=500, verbose_name='message')),
                ('video', models.FileField(default='hero/default.mp4', upload_to='hero/')),
                ('open_date', models.DateTimeField(verbose_name="date d'ouverture")),
                ('close_date', models.DateTimeField(verbose_name='date de cloture')),
                ('register_date', models.DateTimeField(verbose_name="date d'inscription")),
            ],
            options={
                'verbose_name': 'Bienvenu',
                'db_table': 'Hero',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Credit')),
                ('duration', models.CharField(max_length=60, verbose_name='Durée')),
                ('level', models.CharField(max_length=100, null=True, verbose_name='Niveau')),
                ('description', tinymce.models.HTMLField(null=True, verbose_name='Description')),
                ('condition', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='program_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Temoin')),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('almni', 'Ancien élève'), ('student', 'Elève'), ('staff', 'cadre')], max_length=60, verbose_name='Role')),
                ('content', tinymce.models.HTMLField(null=True, verbose_name='Temoignage')),
                ('image', models.ImageField(null=True, upload_to='testimonial_images/')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'db_table': 'testimonial',
            },
        ),
        migrations.CreateModel(
            name='Actuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('hours', models.TimeField(null=True)),
                ('place', models.CharField(max_length=100, null=True, verbose_name='Lieu')),
                ('category', models.CharField(choices=[('DIV_FESTIVAL', 'Festivals'), ('DIV_THEATRE', 'Théâtre & spectacles'), ('DIV_CINEMA', 'Cinéma & projections'), ('DIV_EXPO', 'Expositions & musées'), ('DIV_MODE', 'Mode & défilés'), ('EDU_CONF', 'Conférences'), ('EDU_ATELIER', 'Ateliers / Workshops'), ('EDU_COURS', 'Cours & Formations'), ('EDU_LIVRE', 'Lancements de livres'), ('BUS_FORUM', 'Forums'), ('BUS_SALON', 'Salons professionnels'), ('BUS_NET', 'Networking'), ('SPO_MATCH', 'Matchs & compétitions'), ('SPO_TOURNOI', 'Tournois'), ('SPO_RANDO', 'Randonnées'), ('SOC_MARIAGE', 'Mariages'), ('SOC_ANNIV', 'Anniversaires'), ('SOC_SOIREE', 'Rencontres & soirées'), ('COM_MANIF', 'Manifestations / Marches'), ('COM_FONDS', 'Collectes de fonds'), ('COM_CARIT', 'Actions caritatives'), ('COM_ASSO', 'Événements associatifs')], default='DIV_FESTIVAL', max_length=255, null=True, verbose_name='Categorie')),
                ('date', models.DateTimeField(null=True, verbose_name="date et heure d'ouverture")),
                ('end', models.TimeField(null=True, verbose_name='heure de cloture')),
                ('image', models.ImageField(null=True, upload_to='actuality_images/')),
                ('description', tinymce.models.HTMLField(null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('facilitator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
            ],
            options={
                'verbose_name': 'Evenement',
                'verbose_name_plural': 'Evenements',
                'db_table': 'actuality',
            },
        ),
    ]
