"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$xfnk$i7d6!-^l0xz-lhe$c#e2yfr_@wsipfs4*ftk27&79bx5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

ADMIN_SITE_HEADER = "Panneau d'administration"
ADMIN_SITE_TITLE = "Administration While Educ"


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #app_local
    'core',
    'phonenumber_field',
    'staff',
    'students',
    'accounts', 
    'education',
    'finance',
    'general',
    'tinymce',
    
    #rest_framework
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
               
                'accounts.context_processors.student_context',
                'general.context_processors.contact_context',
                'core.context_processors.core_context',
                'core.context_processors.staff_context'
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "theme": "darkly",  # Mode sombre par défaut (Jazzmin)
    "dark_mode_theme": "darkly",  # Thème sombre (fallback)

    # -- Titres et marques --
    "site_title": "Administration",       # Titre de la fenêtre du navigateur
    "site_header": "Administration", # Titre sur l'écran de connexion
    "site_brand": "Admin",             # Titre dans la barre de navigation
    "welcome_sign": "Bienvenue dans l'administration",

    # -- Logos et icônes (chemins dans vos fichiers statiques) --
    # Note: Jazzmin attend typiquement un chemin relatif à STATICFILES (donc sans "static/")
    # D'après le repo, les assets sont dans: static/assets/img/
    "site_logo": "assets/img/log.png",    # Logo dans la barre de navigation
    "login_logo": "None", # Logo sur la page de connexion
    "site_icon": "assets/img/favicon.png", # Favicon


 

    # -- Menu latéral (Side Menu) --
    "show_sidebar": True,
    "navigation_expanded": False, # Menu déroulant par défaut
    "hide_apps": [],             # Apps à masquer (ex: ["auth"])
    "hide_models": [],           # Modèles à masquer (ex: ["auth.user"])
    "order_with_respect_to": ["auth", "monapp"], # Tri des apps/modèles
    # custom_links: à configurer selon vos vraies vues/permissions.
    # Retiré ici pour éviter des liens cassés (ex: admin:monapp_rapport inexistant).
    "custom_links": {},


    # -- Format des formulaires de modification --
    "changeform_format": "horizontal_tabs",   # Options: "single", "vertical_tabs", "collapsible", "carousel"
    "changeform_format_overrides": {
        "auth.user": "vertical_tabs",
        "auth.group": "collapsible",
    },

    # -- UI Builder (pour personnaliser l'interface visuellement) --
    "show_ui_builder": False,
}
